// Dialogue Conversation Messages
msg = [
	["Hello There!", "???", sNPCFrame],
	["My name is Tom, it's nice to meet you.", "Tom", sNPCFrame],
	["The theme is open ended, so I decided to ask you some open ended questions.", "Tom", sNPCFrame],
	["That's boring", "You (Player)", sPlayer],
	["I know it is.", "Tom", sNPCFrame],
	["I thought this would be a more creative idea.", "Tom", sNPCFrame],
	["So uhh what are the questions?", "You (Player)", sPlayer],
	["Alright let's start with the first question", "Tom", sNPCFrame],
	["What is your favourite part about your day to day routine?", "Tom", sNPCFrame],
	["Second question", "Tom", sNPCFrame],
	["What is currently on your mind that you need to address?", "Tom", sNPCFrame],
	["Last question", "Tom", sNPCFrame],
	["What makes you who you are?", "Tom", sNPCFrame],
	["Take time out of your day to address these questions", "Tom", sNPCFrame],
	["Think about them.", "Tom", sNPCFrame],
	["And improve your lifestyle.", "Tom", sNPCFrame],
	["So your idea of open-minded was open-minded questions?", "You (Player)", sPlayer],
	["Exactly that. There's nothing wrong with it.", "Tom", sNPCFrame],
	["As we are going into 2022 we should improve ourselves.", "Tom", sNPCFrame],
	["The first step is to act on questions that can benefit your lifestyle.", "Tom", sNPCFrame],
	["Ponder over these questions in your spare time.", "Tom", sNPCFrame],
	["Thanks I guess", "You (Player)", sPlayer],
	["By the way", "Tom", sNPCFrame],
	["What is it?", "You (Player)", sPlayer],
	["Do you know who the best hack club member is?", "Tom", sNPCFrame],
	["Vraj Patel.", "Tom", sNPCFrame],
	["ok..... ratio + carti better", "You (Player)", sPlayer],
	["no.", "Tom", sNPCFrame],
]